<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Where_l</name>
   <tag></tag>
   <elementGuidId>c29f4d66-9f1d-4d73-9843-30d0bb94de8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text-input-where</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text-input-where']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ff5d2cd-38a7-48c5-9173-909b54f4db7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>18e66f8b-9cc3-4607-ab09-c0b0e0e603c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label-text-input-where</value>
      <webElementGuid>e3061ccf-2449-4f25-a905-577d8ae8a549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text-input-where</value>
      <webElementGuid>7b38a97a-4d7a-403b-b5dd-c63bf0841e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>l</value>
      <webElementGuid>8c217ff7-882d-440b-9a92-7ad01cb5d905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>District or Province in Thailand</value>
      <webElementGuid>04a72f22-8d92-4502-b09f-7fc09b5d4c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3b1269a3-8643-47e5-8427-94d3cf3aa849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>text-input-where-suggestion-list</value>
      <webElementGuid>cb2f697d-6e16-4688-b1b6-005ee37e0b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icl-TextInput-control</value>
      <webElementGuid>ee345d4b-dbf8-4ce2-8d05-20e185f3c369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>44528c9d-a716-4180-ad17-6810b4da9495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-input-where&quot;)</value>
      <webElementGuid>05dfcf94-d654-48a8-8e3c-e22f3346359b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text-input-where']</value>
      <webElementGuid>50589b4f-841a-47ff-88c4-7890549df4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='jobsearch']/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>ce3f3617-9d90-437c-9dcb-d8a29dd777f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>3ba68bbc-8841-4cf8-a459-013d59c0de75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text-input-where' and @name = 'l' and @placeholder = 'District or Province in Thailand']</value>
      <webElementGuid>95ad1c71-4144-44ce-95b3-ab94fc17fd8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
