<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_What_q</name>
   <tag></tag>
   <elementGuidId>e5408147-0f25-4402-bb64-a51fb0cdf799</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text-input-what</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text-input-what']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36573a5d-8bb5-48cf-9a04-cdb8b1403547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2003be53-9f60-4fa5-ada0-34d026c21989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label-text-input-what</value>
      <webElementGuid>c38a28f4-ad4f-492f-9ef1-6ea971bbdd7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text-input-what</value>
      <webElementGuid>279c8ddb-594b-4a91-83f7-b4411c879eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>4f73634a-be3d-494f-9740-739fac6c8456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Job title, keywords, or company</value>
      <webElementGuid>b625bade-20ef-40a4-aa61-ca2a17fab01c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8eb88985-b40e-4a65-96ab-3d6aaa05aa18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>text-input-what-suggestion-list</value>
      <webElementGuid>c64e762f-b059-450d-9c7e-01da5d8349ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icl-TextInput-control</value>
      <webElementGuid>9df7e3c4-f496-4c8d-bb01-7d96eb085bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c88bd96d-add6-4370-a605-9ecc92c5ce42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-input-what&quot;)</value>
      <webElementGuid>d4dfb44c-e81a-496d-ae4d-a104541c9be2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text-input-what']</value>
      <webElementGuid>d55a9cb8-e245-40ac-9b47-bf750f121724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='jobsearch']/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>25ee76e6-56ab-48bd-9242-b146d9f0babd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c9fc4acf-c9b9-4022-8542-7a4da6c931a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text-input-what' and @name = 'q' and @placeholder = 'Job title, keywords, or company']</value>
      <webElementGuid>dc450618-5009-4dec-812f-c12fc89e58df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
